### ISSUE TITLE
Adding "Hashtag" widget to a dashboard gives an exception

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#1002]
**Description:**
When the "Hashtag" widget is added to a dashboard following exception is observed in the backend.

[2018-08-09 14:48:21,299] ERROR {org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint} - Error initializing the data provider endpoint for source type RDBMSBatchDataProvider. SQL exception occurred Table "HASHTAG" not found; SQL statement:
select trackwords from hashTag ORDER BY id DESC LIMIT 30 [42102-196] org.wso2.carbon.data.provider.exception.DataProviderException: SQL exception occurred Table "HASHTAG" not found; SQL statement:
select trackwords from hashTag ORDER BY id DESC LIMIT 30 [42102-196]
	at org.wso2.carbon.data.provider.rdbms.AbstractRDBMSDataProvider.init(AbstractRDBMSDataProvider.java:142)
	at org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint.onMessage(DataProviderEndPoint.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.executeMethod(MSF4JWSConnectorListener.java:359)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.lambda$handleTextWebSocketMessage$61(MSF4JWSConnectorListener.java:193)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.handleTextWebSocketMessage(MSF4JWSConnectorListener.java:174)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.onMessage(MSF4JWSConnectorListener.java:87)
	at org.wso2.transport.http.netty.contractimpl.HttpWsServerConnectorFuture.notifyWSListener(HttpWsServerConnectorFuture.java:115)
	at org.wso2.transport.http.netty.listener.WebSocketSourceHandler.notifyTextMessage(WebSocketSourceHandler.java:198)
	at org.wso2.transport.http.netty.listener.WebSocketSourceHandler.channelRead(WebSocketSourceHandler.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.wso2.transport.http.netty.listener.WebSocketServerHandshakeHandler.channelRead(WebSocketServerHandshakeHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.wso2.transport.http.netty.listener.UriAndHeaderLengthValidator.channelRead(UriAndHeaderLengthValidator.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1336)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Table "HASHTAG" not found; SQL statement:
select trackwords from hashTag ORDER BY id DESC LIMIT 30 [42102-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5552)
	at org.h2.command.Parser.readTableFilter(Parser.java:1266)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
	at org.h2.command.Parser.parseSelect(Parser.java:1743)
	at org.h2.command.Parser.parsePrepared(Parser.java:449)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:293)
	at org.h2.command.Parser.prepareCommand(Parser.java:258)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:265)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.prepareStatement(HikariConnectionProxy.java)
	at org.wso2.carbon.data.provider.rdbms.AbstractRDBMSDataProvider.init(AbstractRDBMSDataProvider.java:116)
	... 55 more

[2018-08-09 14:48:21,301] ERROR {org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint} - Error found in method : org.wso2.carbon.data.provider.exception.DataProviderException: SQL exception occurred Table "HASHTAG" not found; SQL statement:
select trackwords from hashTag ORDER BY id DESC LIMIT 30 [42102-196]

**Affected Product Version:**
4.0.28-SNAPSHOT

**Steps to reproduce:**
1. Create a dashboard and drag and drop "Hashtag" widget

**Comment by TanyaM** [comment]
Siddhi apps needs to be deployed as a pre-requisite. That message is given in the widget body as "For the processing of "Twitter Analytics" please deploy the Siddhi app as per instructions."
But the instructions page that is linked gives a 404

**Comment by this** [comment]
Seems like this issue is within the [Hashtag](https://github.com/wso2/carbon-analytics/tree/master/components/org.wso2.carbon.sp.solutions/org.wso2.carbon.sp.solutions.twitter.analytics/widgets/Hashtag) widget rather in the `carbon-dashboards`. So lets move this issue to [carbon-analytics](https://github.com/wso2/carbon-analytics/issues).
