### ISSUE TITLE
Exception is thrown intermittently when we designing a new dashboard

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#751]
**Description:**
When we designing a new dashboard,  Following exception is thrown intermittently

[2017-12-12 13:06:44,722] ERROR {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Error in http connector listener java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Suggested Labels:**
Minor

**Suggested Assignees:**
@lasanthaS 
**Affected Product Version:**
wso2sp-4.0.0-beta3
**OS, DB, other environment details and versions:** 
  Ubuntu 16.04.3 LTS

**Comment by suganyasuven** [comment]
Above error logs doesn't occur in v4.0.6 version.

**Comment by CharukaK** [comment]
This error occurs in v4.0.8 when saving a dashboard

Steps to reproduce:
1. Open a dashboard in the design view
2. Do some changes and save.
3. As soon as you saved press the back button
