### ISSUE TITLE
Requesting a non existing dashboard's setting page throws an exception [Exception is intermittent]

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#832]
**Description:**
Following exception is thrown when we request a settings page of a non existing dashboard.

[2017-12-22 11:40:33,150]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.NullPointerException
	at org.wso2.carbon.analytics.permissions.internal.impl.DefaultPermissionProvider.lambda$getGrantedRoles$1(DefaultPermissionProvider.java:254)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.analytics.permissions.internal.impl.DefaultPermissionProvider.getGrantedRoles(DefaultPermissionProvider.java:254)
	at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.getDashboardRoles(DashboardMetadataProviderImpl.java:253)
	at org.wso2.carbon.dashboards.api.internal.DashboardRestApi.getDashboardRoles(DashboardRestApi.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:217)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Affected Product Version:**
4.0.7

**Steps to reproduce:**
1. Go to the dashboard listing and click on settings of a desired dashboard (say dashboard name is foo so the url you will be redirected will be https://<IP>:9643/portal/settings/foo)
2. Change the browser url to https://<IP>:9643/portal/settings/bar

Assumption: There is no dashboard with the url "bar"

Expected behavior is to give a 404 error page. 
Observed behavior : Currently opened settings page gets refreshed with the new url as bar and shows a settings page and an exception is thrown in backend.

**Comment by TanyaM** [comment]
Same is observed for the Design button as well.

**Comment by NisalaNiroshana** [comment]
Resolved with https://github.com/wso2/carbon-dashboards/pull/839
